name: Demo GitHub Actions
on:
  pull_request:
    branches: [ main ]
    
jobs:
  Demo_Workflow:
    runs-on: ubuntu-latest
    
    steps:
      - name: Single-Line Script Sample
        run: echo "Hi! Greetings from Castle Donington!"
        
      - name: Multi-Line Script Sample
        run: |
          echo "Welcome to M&S"
          echo "This is a Demo GitHub Workflow"
